# .circleci/config.yml
version: 2.1

# Require orbs
orbs:
  codecov: codecov/codecov@1.0.4

# Define reusable executors
executors:
  php73cli-alpine: # declares a reusable executor
    docker:
      - image: jeckel/php-test:7.3-cli-alpine
    working_directory: /home/circleci/project

  php73cli-stretch: # declares a reusable executor
    docker:
      - image: jeckel/php-test:7.3-cli-stretch
    working_directory: /home/circleci/project

# Configure Jobs:
jobs:
  composer:
    executor: php73cli-alpine
    steps:
      - checkout

      - restore_cache:
          name: Restore composer's vendor cache
          keys:
            - vendor-v1-{{ checksum "composer.lock" }}
      - run:
          name: Install composer deps
          command: composer install --no-suggest --no-interaction --ignore-platform-reqs
      - save_cache:
          name: Save composer's vendor in cache
          key: vendor-v1-{{ checksum "composer.lock" }}
          paths:
            - "vendor"
      - persist_to_workspace:
          root: /home/circleci
          paths: project

  codeception:
    executor: php73cli-stretch
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Codeception
          command: vendor/bin/codecept run --coverage --coverage-html --coverage-xml

      - codecov/upload:
          file: tests/_output/coverage.xml

      - store_artifacts:
          path: tests/_output

  phpstan:
    executor: php73cli-alpine
    steps:
      - attach_workspace:
        at: /home/circleci
              - run:
              name: PHP Stan
              command: vendor/bin/phpstan analyse

  phpcs:
    executor: php73cli-alpine
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: PHP Code Sniffer
          command: vendor/bin/phpcs

  phpmd:
    executor: php73cli-alpine
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: PHP Mess Detector
          command: vendor/bin/phpmd src text cleancode,codesize,design,naming,unusedcode

  builds_completed:
    docker:
      - image: docker:git
    steps:
      - run: echo "Builds completed with success"

# Define the workflow:
workflows:
  version: 2
  build:
    jobs:
      - composer
      - codeception:
          requires:
            - composer
      - phpstan:
          requires:
            - composer
      - phpcs:
          requires:
            - composer
      - phpmd:
          requires:
            - composer
      - builds_completed:
          requires:
            - codeception
            - phpstan
            - phpcs
            - phpmd
